# Data Analysis Foundations
This notebook introduces numerical computing with NumPy and data analysis with pandas, covering arrays, DataFrames, data loading, filtering, aggregation, statistics, and basic data cleaning. 

We will focus on the following:

- Arrays and vectorised operations

- Series and DataFrames

- Loading structured datasets

- Filtering and aggregation

- Descriptive statistics

- Basic data cleaning

## Why **NumPy**?

Python lists are flexible but not efficient for numerical computing.

**NumPy** provides:

- Fast numerical arrays

- Vectorised computation

- Mathematical functions implemented in C (high performance)

In [2]:
#Required installations for NumPy & pandas
"You should expect an output like (Requirement already satisfied: ....)"
!pip install numpy
!pip install pandas

In [3]:
# np.array() converts a Python list into a NumPy array.
import numpy as np
sales_list= [200, 150,100, 140, 220, 180, 179]
sales = np.array(sales_list)
print(sales)
print ("Type of sales:", type(sales))

[200 150 100 140 220 180 179]
Type of sales: <class 'numpy.ndarray'>


In [36]:
# A function that creates an array with a range of numbers
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [37]:
# A function that generates 6 evenly spaced numbers between 0 and 1 (inclusive).
"""#- Start value: 0
   - End value: 1
   - Number of elements: 6"""
arr = np.linspace(0, 1, 6)
print(arr) 

[0.  0.2 0.4 0.6 0.8 1. ]


### Vectorised Operations 
Vectorisation in **NumPy** refers to applying operations on entire arrays without using explicit loops. 

In [38]:
# computation of common descriptive statistics using vectorised NumPy operations

# total sum of all elements in the sales array
total = sales.sum()

# arithmetic mean of all elements in the sales array
mean = sales.mean()

# standard deviation of the sales distribution
std_dev = sales.std()

# output of computed summary statistics
print("Total:", total)
print("Mean:", mean)
print("Standard deviation:", std_dev)

Total: 1169
Mean: 167.0
Standard deviation: 37.25970630970827


In [39]:
# Step-by-step computation of Standard Deviation **(for basic understanding purpose)**

# step 1: compute the mean
mean = sales.mean()

# step 2: compute deviations from the mean
deviations = sales - mean

# step 3: square the deviations
squared_deviations = deviations ** 2

# step 4: compute the variance (average of squared deviations)
variance = squared_deviations.mean()

# step 5: standard deviation is the square root of variance
std_dev = np.sqrt(variance)

print("Mean:", mean)
print("Deviations:", deviations)
print("Squared deviations:", squared_deviations)
print("Variance:", variance)
print("Standard deviation:", std_dev)

Mean: 167.0
Deviations: [ 33. -17. -67. -27.  53.  13.  12.]
Squared deviations: [1089.  289. 4489.  729. 2809.  169.  144.]
Variance: 1388.2857142857142
Standard deviation: 37.25970630970827


In [40]:
# Aggregation Functions
A = np.array([[1, 2],  #2D Array
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Sum of all Elements
print("Sum of all elements in A", A.sum())
# Mean (Average)
print("Average of all elements in B", B.mean())
#  Standard deviation of all elements
print("Standard deviation of all elements in B", B.std())
# Min
print("Minimum element value in B", B.min())
# Max
print("Maximum element value in A", A.max())

Sum of all elements in A 10
Average of all elements in B 6.5
Standard deviation of all elements in B 1.118033988749895
Minimum element value in B 5
Maximum element value in A 4


### Element-wise Operations

With **NumPy**, you can perform math operations directly on arrays! **No need for loops**.

- Addition
- Subtraction
- Multiplication
- Division

In [41]:
a = np.array([22, 23, 24])
b = np.array([2, 3, 4])

# Element-wise addition - 22+2, 23+3, 24+4
print(a + b)  

# Element-wise subtraction - 22-2, 23-3, 24-4
print(a-b) 

# Element-wise multiplication - 22*2, 23*3, 24*4
print(a * b)  

# Element-wise division - 2/22, 3/23, 4/2
print(b / a)  

[24 26 28]
[20 20 20]
[44 69 96]
[0.09090909 0.13043478 0.16666667]


In [44]:
'''Look at the output of each operation'''
A = np.array([[1, 2],   
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Element-wise addition - 1+5 , 2+6
#                         3+7, 4+8
print("Element-wise addition",A+B)  

# Element-wise subtraction- 5-1 , 6-2
#                         7-3, 8-4
print("Element-wise subtraction",B-A) 

# Element-wise multiplication - 1*5 , 2*6
#                         3*7, 4*8
print("Element-wise multiplication",A*B)  

# Element-wise division 5/1 , 6/2
#                         7/3, 8/4
print("Element-wise division",B/A)  

Element-wise addition [[ 6  8]
 [10 12]]
Element-wise subtraction [[4 4]
 [4 4]]
Element-wise multiplication [[ 5 12]
 [21 32]]
Element-wise division [[5.         3.        ]
 [2.33333333 2.        ]]


In [45]:
# Dot Product operation
"""The result is calculated by multiplying corresponding elements 
in a row of A with a column of B and summing them."""
""" [(1*5)+(2*7)  (1*6)+(2*8)
     (3*5)+(4*7)  (3*6)+(4*8)]"""

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Using np.dot()
print("np.dot(A, B)",np.dot(A, B))

# Or using the '@' operator (more Pythonic)
print("A @ B",A @ B)

np.dot(A, B) [[19 22]
 [43 50]]
A @ B [[19 22]
 [43 50]]


In [46]:
# Matrix Transpose
"""Flipping a matrix over its diagonal. Rows become columns, and columns become rows."""
Original_Matrix= np.array([[19, 22],
                           [43, 50]])
Transposed_Matrix= Original_Matrix.T
print(Transposed_Matrix)

[[19 43]
 [22 50]]


### Scalar Operations
You can add or multiply every number in the array by a single value using scalar operations.

In [61]:
print(A + 20)  
print (B-1)

[[21 22]
 [23 24]]
[[4 5]
 [6 7]]


In [62]:
print(A*2)
print(B/2)

[[2 4]
 [6 8]]
[[2.5 3. ]
 [3.5 4. ]]


### Broadcasting
This allows *NumPy* to perform operations on arrays of different shapes without making copies of data.  *NumPy*  automatically stretches the smaller array to match the shape of the larger one.

In [63]:
# increase all sales values by 10 percent and store the updated results
updated_sales = sales * 1.10
# display the updated sales array
print(updated_sales)

[220.  165.  110.  154.  242.  198.  196.9]


In [49]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([1, 0, 1])

# Adding 'b' (smaller array) to each row of 'a' (larger array)
result = b+a
print(result)

[[2 2 4]
 [5 5 7]]


### Boolean Indexing
 With Boolean indexing, you can filter elements in an array based on conditions.

In [65]:
# Working with Conditions in NumPy
one_arr = np.array([1, 2, 3, 4, 5, 6])

'''Get elements greater than 3
     one_arr > 3 creates a Boolean array and NumPy uses this to return only the elements where the condition is True '''
result = one_arr[one_arr > 3]
print(result)  

[4 5 6]


In [ ]:
# Working with Conditions in NumPy
two_arr = np.array([[12, 22, 32],
              [42, 52, 26]])

# Get elements greater than 12
result = two_arr[two_arr > 12]
print(result) # output in 1D

In [64]:
# Working with multiple conditions in NumPy
two_arr = np.array([[12, 22, 32], [42, 52, 26]])

result = two_arr[(two_arr > 12) & (two_arr < 50)]
print(result)

[22 32 42 26]


In [66]:
# Conditional Operations with where() - It’s like an if-else for arrays.
labeled_arr = np.array([100, 202, 150, 115, 160])

# Label elements as 'High' if >150, otherwise 'Low'
result = np.where(labeled_arr > 150, 'High', 'Low')
'''Breakdown:
Condition: labeled_arr > 150
If True, return 'High'
If False, return 'Low'
'''
print(result)  

['Low' 'High' 'Low' 'Low' 'High']


In [ ]:
# Conditional Operations with where() - It’s like an if-else for arrays.
labeled_arr = np.array([100, 202, 150, 115, 160])

# replace elements greater than 150 with 250 , otherwise 0
result = np.where(labeled_arr > 150, 250, 0)
print(result)  

### Set Operations
Set operations in **NumPy** are just like that finding overlaps, differences, and unions.

In [67]:
# unique()- No duplicates, just clean data
a = np.array([12, 22, 22, 23, 24, 24, 52])
print(np.unique(a))

[12 22 23 24 52]


In [69]:
# intersect1d() - Find Common Elements
a = np.array([12, 22, 23, 42])
b = np.array([23, 42, 25, 62])
# Common elements
print(np.intersect1d(a, b)) 

[23 42]


In [ ]:
# union1d() - Combine Arrays (No Duplicates)
a = np.array([12, 22, 23, 42])
b = np.array([23, 42, 25, 62])
# union of both arrays
print(np.union1d(a, b)) 

In [ ]:
# setdiff1d() - Find Differences
a = np.array([12, 22, 23, 42])
b = np.array([23, 42, 25, 62])
# merges both arrays, removing duplicates.
print(np.setdiff1d(a, b)) 
print(np.setdiff1d(b, a)) 

In [ ]:
# array_split (arr, num)
a = np.array([12, 22, 23, 42])
newarr = np.array_split(a, 4)
print(newarr)

In [ ]:
# sort(arr) 
a = np.array([132, 22, 23, 42])
newarr = np.sort(a)
print(newarr)

In [68]:
# Unique in 2d array
A = np.array([[1, 23],  
              [23, 4]])

B = np.array([[51, 22],
              [22, 8]])
print(np.unique(A))
print (np.unique(B))

[ 1  4 23]
[ 8 22 51]


In [72]:
# Flatten the 2d array
A = np.array([[1, 23],  
              [23, 4]])
print(A.flatten())


[ 1 23 23  4]


In [ ]:
# Union in 2d arrays
A = np.array([[1, 23],  
              [23, 4]])

B = np.array([[51, 22],
              [22, 8]])
# To get the union of two arrays, use np.union1d
# First we need to flatten the arrays or not
print(np.union1d(A.flatten(), B.flatten()))
print(np.union1d(A,B))

[ 1  4 23]
[ 8 22 51]
[ 1  4  8 22 23 51]
[ 1  4  8 22 23 51]


In [77]:
# intersection in 2d arrays
A = np.array([[1, 22],  
              [23, 4]])

B = np.array([[51, 22],
              [23, 8]])
# To get the intersection of two arrays, use np.intersect1d
# First we may flatten the arrays (optional)
print(np.intersect1d(A.flatten(), B.flatten()))
# or directly use intersect1d
print(np.intersect1d(A, B))

[22 23]
[22 23]


In [76]:
# difference in 2d arrays  
A = np.array([[1, 22],  
              [23, 4]])

B = np.array([[51, 22],
              [23, 8]])
# Flatten the arrays and use np.unique to get unique values
# This is equivalent to a union operation for a single array
print(np.unique(A))
print(np.unique(B))

# To get the intersection of two arrays, use np.setdiff1d
# First we may flatten the arrays or not
print(np.setdiff1d(A.flatten(), B.flatten()))
print(np.setdiff1d(A, B))
print(np.setdiff1d(B.flatten(), A.flatten()))
print(np.setdiff1d(B, A))

[ 1  4 22 23]
[ 8 22 23 51]
[1 4]
[1 4]
[ 8 51]
[ 8 51]


In [84]:
# reshape a NumPy array

A = np.array([[1, 22],  
              [23, 4]])

# reshape from 2x2 to 4x1
reshaped_A = np.reshape(A, (4, 1)) 
print(reshaped_A)

[[ 1]
 [22]
 [23]
 [ 4]]


In [85]:
# Error with reshape 
# can't reshape 3x4 to 3x3
C = np.array([[1, 2, 3,7], 
              [4, 5, 6,8],
              [7, 8, 9,10]])
reshaped_C = np.reshape(C, (3, 3))
print(reshaped_C) #ValueError: cannot reshape array of size 12 into shape (3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

## Pandas Series

A Series is:

- One-dimensional

- Labelled

- Built on NumPy

In [2]:
# pandas series syntax
import pandas as pd

'''First argument → data
   index → labels
'''

expenses = pd.Series(
     [450, 520, 610, 490, 580, 700],
    index=["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
   
)

print(expenses)

Jan    450
Feb    520
Mar    610
Apr    490
May    580
Jun    700
dtype: int64


In [10]:
# total expense
print("Total:", expenses.sum())
# average
print("Average:", expenses.mean())
# label of maximum value
print("Highest month:", expenses.idxmax())

Total: 3350
Average: 558.3333333333334
Highest month: Jun


In [11]:
# Filtering a Series
high_expenses = expenses[expenses > 500] #Same Boolean logic as NumPy.
print(high_expenses)

Feb    520
Mar    610
May    580
Jun    700
dtype: int64


## Pandas DataFrame

A DataFrame:

- Two-dimensional

- Columns can have different types

- Similar to Excel table

In [5]:
# creating a DataFrame
data = {
    "name": ["Alice", "Bob", "Charlie", "Diana"],
    "age": [23, 25, 22, 24],
    "grade": [85, 48, 72, 90],
    "attendance": [92, 80, 85, 95]
}
'''
- Dictionary keys become column names.
- Each list becomes a column.
- Rows are automatically indexed.
'''
df = pd.DataFrame(data)
print(df)

      name  age  grade  attendance
0    Alice   23     85          92
1      Bob   25     48          80
2  Charlie   22     72          85
3    Diana   24     90          95


In [13]:
# inspecting Data - df.head()
print(df.head()) # returns the first 5 rows if a number is not specified.

      name  age  grade  attendance
0    Alice   23     85          92
1      Bob   25     48          80
2  Charlie   22     72          85
3    Diana   24     90          95


In [14]:
# inspecting Data - df.head()
print(df.head(1)) # returns the first row

    name  age  grade  attendance
0  Alice   23     85          92


In [15]:
# inspecting Data - df.info()
'''
The information contains the number of columns, column labels, column data types, memory usage, 
range index, and the number of cells in each column (non-null values).
'''
print(df.info()) #prints information about the DataFrame.

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      str  
 1   age         4 non-null      int64
 2   grade       4 non-null      int64
 3   attendance  4 non-null      int64
dtypes: int64(3), str(1)
memory usage: 280.0 bytes
None


In [16]:
# inspecting Data - df.describe()
'''
The description contains these information for each column:
count - The number of not-empty values.
mean - The average (mean) value.
std - The standard deviation.
min - the minimum value.
Percentiles are used in statistics to give you a number that describes the value that a given percent of the values are lower than.
25% - The 25% percentile*.
50% - The 50% percentile*.
75% - The 75% percentile*.
max - the maximum value.
'''
print(df.describe()) 

             age      grade  attendance
count   4.000000   4.000000     4.00000
mean   23.500000  73.750000    88.00000
std     1.290994  18.768324     6.78233
min    22.000000  48.000000    80.00000
25%    22.750000  66.000000    83.75000
50%    23.500000  78.500000    88.50000
75%    24.250000  86.250000    92.75000
max    25.000000  90.000000    95.00000


In [17]:
# creating new columns
df["passed"] = df["grade"] >= 50
print(df)

      name  age  grade  attendance  passed
0    Alice   23     85          92    True
1      Bob   25     48          80   False
2  Charlie   22     72          85    True
3    Diana   24     90          95    True


In [18]:
# selecting data - select column
print(df["grade"])

0    85
1    48
2    72
3    90
Name: grade, dtype: int64


In [ ]:
# filter rows
passed_students = df[df["grade"] >= 50]
print(passed_students)

In [7]:
# refer to the row index using loc[index]
print(df.loc[0])

name          Alice
age              23
grade            85
attendance       92
Name: 0, dtype: object


In [6]:
print(df.loc[[0, 1]])

    name  age  grade  attendance
0  Alice   23     85          92
1    Bob   25     48          80


In [8]:
# Named Indexes
df = pd.DataFrame(data, index = ["student1", "student2", "student3","student4"])
print(df)

             name  age  grade  attendance
student1    Alice   23     85          92
student2      Bob   25     48          80
student3  Charlie   22     72          85
student4    Diana   24     90          95


In [ ]:
# Locate named index:
print(df.loc["student2"])

In [9]:
# Load Files into a DataFrame
df = pd.read_csv('csv_file.csv')
print(df)
# Print the first 3 rows of the DataFrame
print(df.head(3)) 
# Print the last 2 rows of the DataFrame
print(df.tail(2)) 

    name  country      city  age
0   Alex      USA  New York   26
1   Adam      USA   Florida   27
2  Harry       UK    London   32
3    Sam   France     Paris   30
4  David  Germany    Berlin   32
    name country      city  age
0   Alex     USA  New York   26
1   Adam     USA   Florida   27
2  Harry      UK    London   32
    name  country    city  age
3    Sam   France   Paris   30
4  David  Germany  Berlin   32


In [12]:
# Creating the first Dataframe using dictionary
df1 = pd.DataFrame({"a":[1, 2, 3, 4],
                    "b":[5, 6, 7, 8]})

# Creating the Second Dataframe using dictionary
df2 = pd.DataFrame({"a":[1, 2, 3],
                    "b":[5, 6, 7],
                    "c":[1, 5, 4]})

# Use pd.concat() to combine dataframes
df1 = pd.concat([df1, df2], ignore_index=True)
df1

,a,b,c
0,1,5,NaN
1,2,6,NaN
2,3,7,NaN
3,4,8,NaN
4,1,5,1.0
5,2,6,5.0
6,3,7,4.0


## Grouping and Aggregation

In [14]:
department_data = {
    "employee": ["A", "B", "C", "D", "E"],
    "department": ["IT", "HR", "IT", "HR", "Finance"],
    "salary": [4000, 3500, 4200, 3700, 5000]
}

df_dep = pd.DataFrame(department_data)
print (df_dep)
'''
- groupby("department") splits data.

- ["salary"] selects column.

- mean() aggregates.
'''
grouped = df_dep.groupby("department")["salary"].mean()
print(grouped)

  employee department  salary
0        A         IT    4000
1        B         HR    3500
2        C         IT    4200
3        D         HR    3700
4        E    Finance    5000
department
Finance    5000.0
HR         3600.0
IT         4100.0
Name: salary, dtype: float64


## Data Cleaning

Real data is messy.

**Common problems**:

- Missing values

- Duplicates

- Wrong data types

- Inconsistent labels

In [21]:
# Fill missing values
department_data = {
    "employee": ["A", "B", "C", "D", "E"],
    "department": ["IT", "HR", "IT", "HR", "Finance"],
    "salary": [4000, 3500, 4200, 3700, 5000]
}

df_dep = pd.DataFrame(department_data)
print(df_dep)

df_missing = df_dep.copy()

# Create a new row as a DataFrame
new_row = pd.DataFrame({"employee": ["F"], "department": ["Finance"], "salary": [None]})

# Use concat to merge old df with the new one
df_missing = pd.concat([df_missing, new_row], ignore_index=True)
pd.set_option('future.no_silent_downcasting', True)
   
print(df_missing)

# Fill missing values with mean
df_missing["salary"] = df_missing["salary"].fillna(df_missing["salary"].mean()).infer_objects(copy=False)
print(df_missing)
   

  employee department  salary
0        A         IT    4000
1        B         HR    3500
2        C         IT    4200
3        D         HR    3700
4        E    Finance    5000
  employee department salary
0        A         IT   4000
1        B         HR   3500
2        C         IT   4200
3        D         HR   3700
4        E    Finance   5000
5        F    Finance   None
  employee department  salary
0        A         IT  4000.0
1        B         HR  3500.0
2        C         IT  4200.0
3        D         HR  3700.0
4        E    Finance  5000.0
5        F    Finance  4080.0


C:\Users\Ghadeer\AppData\Local\Temp\ipykernel_15332\3834884739.py:18: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.set_option('future.no_silent_downcasting', True)
C:\Users\Ghadeer\AppData\Local\Temp\ipykernel_15332\3834884739.py:23: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  df_missing["salary"] = df_missing["salary"].fillna(df_missing["salary"].mean()).infer_objects(copy=False)


In [ ]:
department_data = {
    "employee": ["A", "B", "C", "D", "E"],
    "department": ["IT", "HR", "IT", "HR", "Finance"],
    "salary": [4000, 3500, 4200, 3700, 5000]
}

df_dep = pd.DataFrame(department_data)

df_missing = df_dep.copy()

new_row = pd.DataFrame({"employee": ["F"], "department": ["Finance"], "salary": 5000})
df_missing = pd.concat([df_missing, new_row], ignore_index=True)
df_missing = pd.concat([df_missing, new_row], ignore_index=True)
pd.set_option('future.no_silent_downcasting', True)
print(df_missing)

# Removing Duplicates
df_no_duplicates = df_missing.drop_duplicates()
print(df_no_duplicates)

In [1]:
# Cleaning Strings - If salary contains currency symbol:
department_data = {
    "employee": ["A", "B", "C", "D", "E"],
    "department": ["IT", "HR", "IT", "HR", "Finance"],
    "salary": [4000, 3500, 4200, 3700, 5000]
}
# Create DataFrame (missing in original code)
import pandas as pd
df_dep = pd.DataFrame(department_data)

# Assign messy salary data
df_dep["salary"] = ["€4,000", "€3,500", "4200", " €3,700 ", "€5,000"]
print("\nMessy DataFrame:")
print(df_dep)

# Clean the salary column
df_dep["salary"] = df_dep["salary"].astype(str)
df_dep["salary"] = df_dep["salary"].str.replace("€", "")  # Remove euro symbol
df_dep["salary"] = df_dep["salary"].str.replace(",", "")  # Remove commas
df_dep["salary"] = df_dep["salary"].str.strip()  # Remove leading/trailing spaces
df_dep["salary"] = df_dep["salary"].astype(float)  # Convert to float

print("\nCleaned DataFrame:")
print(df_dep)


Messy DataFrame:
  employee department    salary
0        A         IT    €4,000
1        B         HR    €3,500
2        C         IT      4200
3        D         HR   €3,700 
4        E    Finance    €5,000

Cleaned DataFrame:
  employee department  salary
0        A         IT  4000.0
1        B         HR  3500.0
2        C         IT  4200.0
3        D         HR  3700.0
4        E    Finance  5000.0


### Now we are done with week 6's lab content 🎉🎉🎉 ##
![Week 6](pandas.jpg)
### Let's navigate to Exercise's notebook ⬇️⬇️⬇️
[Exercise Notebook](Week6_Exercise.ipynb)